In [1]:
import torch 

In [16]:
modifier_weights = torch.Tensor([[1,0,0,0,0,0], [0,1,0,0,0,0], [0,0,1,0,0,0], [0,0,0,2,0,0], [0,0,0,0,2,0], [0,0,0,0,0,2]])

#indices = torch.Tensor([[1,0,0,0],[0,0,1,0], [0,0,0,1], [0,1,0,0], [0,0,1,0]])

indices = torch.Tensor([[1,0,0,1,0,0],[0,0,1,0,0,0]])

#batch = torch.Tensor([[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0]])

batch = torch.Tensor([[0,0,0,0,0,0],[0,0,0,0,0,0]])

broadcasted_bias = modifier_weights.unsqueeze(0).expand(len(batch),-1,-1)

broadcasted_bias


tensor([[[1., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 2., 0., 0.],
         [0., 0., 0., 0., 2., 0.],
         [0., 0., 0., 0., 0., 2.]],

        [[1., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 2., 0., 0.],
         [0., 0., 0., 0., 2., 0.],
         [0., 0., 0., 0., 0., 2.]]])

In [17]:
out_expanded = indices.unsqueeze(2)    
out_expanded

tensor([[[1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [0.]]])

In [18]:
result = out_expanded * broadcasted_bias
result

tensor([[[1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 2., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]])

In [19]:
shifted = result.sum(dim=1)
shifted

tensor([[1., 0., 0., 2., 0., 0.],
        [0., 0., 1., 0., 0., 0.]])