In [14]:
import numpy as np

c = [1, 0, 0, 0, 0, 2, 0, 0, 0, 0]
np.add.reduceat(c, np.arange(0, len(c), 5))

array([1, 2])

In [16]:
np.arange(0, len(c), 5)

array([0, 5])

In [17]:
import numpy as np

# Create a 2D array (for example, 10x10)
array_2d = np.array([[1, 0, 0, 0, 0, 2, 0, 0, 0, 0], [1, 0, 0, 0, 0, 2, 0, 0, 0, 0]])  # Replace with your 2D array data

# Define indices for reduction
indices = np.arange(0, array_2d.shape[1], 5)  # Change shape[1] to shape[0] for row-wise operation
print(indices)

# For row-wise reduction:
result_rows = np.add.reduceat(array_2d, indices, axis=1)

print("Row-wise reduction result:", result_rows)


[0 5]
Row-wise reduction result: [[1 2]
 [1 2]]


In [18]:

import torch
tensor_2d = torch.Tensor([[1, 0, 0, 0, 0, 2, 0, 0, 0, 0], [1, 0, 0, 0, 0, 2, 0, 0, 0, 0]])  # Replace with your 2D array data
print(tensor_2d)

# Reshape each row into a 2D tensor of shape (num_rows, num_chunks, 10)
reshaped = tensor_2d.reshape(tensor_2d.size(0), -1, 5).sum(dim=-1)

print(reshaped)

# Sum over the last dimension to sum every 10 elements
#sum_blocks = reshaped.sum(dim=-1)

tensor([[1., 0., 0., 0., 0., 2., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 2., 0., 0., 0., 0.]])
tensor([[1., 2.],
        [1., 2.]])


In [22]:
#expand again sum_blocks to the original shape
sum_blocks = reshaped.unsqueeze(-1).expand(-1, -1, 5)
print(sum_blocks)

tensor([[[1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.]],

        [[1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.]]])


In [30]:
tensor_2d = torch.Tensor([[0.2, 0, 0.8, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0.3, 0, 0, 0, 0, 0.7, 0, 0]])  # Replace with your 2D array data


In [37]:
# Reshape each row into a 2D tensor of shape (num_rows, num_chunks, 10)
reshaped = tensor_2d.reshape(tensor_2d.size(0), -1, 5).sum(dim=-1)
sum_blocks = reshaped.unsqueeze(-1).expand(-1, -1, 5)/10
print(sum_blocks)

tensor([[[0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.0300, 0.0300, 0.0300, 0.0300, 0.0300],
         [0.0700, 0.0700, 0.0700, 0.0700, 0.0700]]])


In [36]:
sum_blocks = reshaped.unsqueeze(-1).expand(-1, -1, 5).reshape(tensor_2d.size(0), -1)
print(sum_blocks)

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.3000, 0.3000, 0.3000, 0.3000, 0.3000, 0.7000, 0.7000, 0.7000, 0.7000,
         0.7000]])
