In [1]:
import torch 

In [9]:
modifier_weights = torch.Tensor([1,0,0,0,0,0])

multiplier = 3

# repeat each element in the array by the number of times you want to multiply

modifier_weights = modifier_weights.repeat_interleave(2)


In [10]:
modifier_weights

tensor([1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
index = torch.tensor([[0, 1, 2, 0]])

In [21]:
torch.zeros(3, 5).scatter_(0, index, 1)

tensor([[1., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

In [31]:
# Example array of indices
indices = torch.tensor([0, 2, 1, 3])

# Number of classes (assuming indices start at 0)
num_classes = indices.max().item() + 1

one_hot = torch.zeros(indices.shape[0], num_classes)
one_hot[torch.arange(indices.shape[0]), indices] = 1

In [32]:
one_hot

tensor([[1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.]])